"""fundacao schema inicial

Revision ID: 0001
Revises: 
Create Date: 2026-10-05 18:41:57.412063
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('actual_reference_year', sa.Integer(), nullable=False),
    sa.Column('opex_deadline', sa.Date(), nullable=True),
    sa.Column('capex_deadline', sa.Date(), nullable=True),
    sa.Column('personnel_deadline', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_cycles')),
    sa.UniqueConstraint('fiscal_year', name=op.f('uq_budget_cycles_fiscal_year'))
    )
    op.create_table('budget_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('roman', sa.String(length=6), nullable=True),
    sa.Column('package_type', sa.Integer(), nullable=False),
    sa.Column('nature', sa.String(length=20), nullable=False),
    sa.Column('form_type', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_packages')),
    sa.UniqueConstraint('code', name=op.f('uq_budget_packages_code'))
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('code', name=op.f('uq_companies_code'))
    )
    op.create_table('contract_types',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('apply_multiplier', sa.Boolean(), nullable=False),
    sa.Column('default_multiplier', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_contract_types'))
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('name', name=op.f('uq_departments_name'))
    )
    op.create_table('job_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('level', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_positions')),
    sa.UniqueConstraint('name', name=op.f('uq_job_positions_name'))
    )
    op.create_table('lookup_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=40), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lookup_values')),
    sa.UniqueConstraint('domain', 'code', name=op.f('uq_lookup_values_domain_code'))
    )
    op.create_index(op.f('ix_lookup_values_domain'), 'lookup_values', ['domain'], unique=False)
    op.create_table('roles',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_roles'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dre_group', sa.String(length=100), nullable=True),
    sa.Column('nature', sa.String(length=20), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['budget_packages.id'], name=op.f('fk_accounts_package_id_budget_packages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('code', name=op.f('uq_accounts_code'))
    )
    op.create_index(op.f('ix_accounts_package_id'), 'accounts', ['package_id'], unique=False)
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_areas_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_areas')),
    sa.UniqueConstraint('name', 'department_id', name=op.f('uq_areas_name_department_id'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=60), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_branches_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branches')),
    sa.UniqueConstraint('company_id', 'code', name=op.f('uq_branches_company_id_code'))
    )
    op.create_index(op.f('ix_branches_company_id'), 'branches', ['company_id'], unique=False)
    op.create_table('budget_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('major', sa.Integer(), nullable=False),
    sa.Column('minor', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('parent_version_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_budget_versions_created_by_users')),
    sa.ForeignKeyConstraint(['cycle_id'], ['budget_cycles.id'], name=op.f('fk_budget_versions_cycle_id_budget_cycles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_version_id'], ['budget_versions.id'], name=op.f('fk_budget_versions_parent_version_id_budget_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_versions')),
    sa.UniqueConstraint('cycle_id', 'major', 'minor', name=op.f('uq_budget_versions_cycle_id_major_minor'))
    )
    op.create_index(op.f('ix_budget_versions_cycle_id'), 'budget_versions', ['cycle_id'], unique=False)
    op.create_table('cycle_parameters',
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['budget_cycles.id'], name=op.f('fk_cycle_parameters_cycle_id_budget_cycles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cycle_id', 'key', name=op.f('pk_cycle_parameters'))
    )
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_type', sa.String(length=30), nullable=True),
    sa.Column('layout', sa.String(length=40), nullable=True),
    sa.Column('file_name', sa.String(length=300), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('warning_rows', sa.Integer(), nullable=False),
    sa.Column('error_rows', sa.Integer(), nullable=False),
    sa.Column('duplicate_rows', sa.Integer(), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], name=op.f('fk_import_batches_confirmed_by_users')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_import_batches_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches'))
    )
    op.create_index(op.f('ix_import_batches_file_sha256'), 'import_batches', ['file_sha256'], unique=False)
    op.create_index(op.f('ix_import_batches_status'), 'import_batches', ['status'], unique=False)
    op.create_table('package_managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('manager_name', sa.String(length=200), nullable=False),
    sa.Column('scope_label', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_package_managers_company_id_companies')),
    sa.ForeignKeyConstraint(['cycle_id'], ['budget_cycles.id'], name=op.f('fk_package_managers_cycle_id_budget_cycles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_id'], ['budget_packages.id'], name=op.f('fk_package_managers_package_id_budget_packages')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_package_managers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_managers'))
    )
    op.create_index(op.f('ix_package_managers_cycle_id'), 'package_managers', ['cycle_id'], unique=False)
    op.create_table('personnel_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('salary_adjustment_pct', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('adjustment_month', sa.SmallInteger(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_personnel_scenarios_created_by_users')),
    sa.ForeignKeyConstraint(['cycle_id'], ['budget_cycles.id'], name=op.f('fk_personnel_scenarios_cycle_id_budget_cycles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personnel_scenarios'))
    )
    op.create_table('travel_fares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=60), nullable=False),
    sa.Column('destination', sa.String(length=60), nullable=False),
    sa.Column('trip_type', sa.String(length=30), nullable=False),
    sa.Column('round_trip_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['budget_cycles.id'], name=op.f('fk_travel_fares_cycle_id_budget_cycles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_travel_fares')),
    sa.UniqueConstraint('cycle_id', 'origin', 'destination', name=op.f('uq_travel_fares_cycle_id_origin_destination'))
    )
    op.create_table('travel_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('rate_type', sa.String(length=20), nullable=False),
    sa.Column('trip_type', sa.String(length=30), nullable=False),
    sa.Column('job_level', sa.String(length=60), nullable=False),
    sa.Column('daily_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['budget_cycles.id'], name=op.f('fk_travel_rates_cycle_id_budget_cycles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_travel_rates')),
    sa.UniqueConstraint('cycle_id', 'rate_type', 'trip_type', 'job_level', name=op.f('uq_travel_rates_cycle_id_rate_type_trip_type_job_level'))
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_code', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['role_code'], ['roles.code'], name=op.f('fk_user_roles_role_code_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_code', name=op.f('pk_user_roles'))
    )
    op.create_table('account_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_account_details_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_details')),
    sa.UniqueConstraint('account_id', 'name', name=op.f('uq_account_details_account_id_name'))
    )
    op.create_table('asset_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_asset_classes_account_id_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_classes')),
    sa.UniqueConstraint('name', name=op.f('uq_asset_classes_name'))
    )
    op.create_table('benefit_types',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('calc_mode', sa.String(length=20), nullable=False),
    sa.Column('default_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_benefit_types_account_id_accounts')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_benefit_types'))
    )
    op.create_table('cost_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('manager_user_id', sa.Integer(), nullable=True),
    sa.Column('manager_name', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('is_csc', sa.Boolean(), nullable=False),
    sa.Column('is_backoffice', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name=op.f('fk_cost_centers_area_id_areas')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_cost_centers_company_id_companies')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_cost_centers_department_id_departments')),
    sa.ForeignKeyConstraint(['manager_user_id'], ['users.id'], name=op.f('fk_cost_centers_manager_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cost_centers')),
    sa.UniqueConstraint('company_id', 'code', name=op.f('uq_cost_centers_company_id_code'))
    )
    op.create_index(op.f('ix_cost_centers_code'), 'cost_centers', ['code'], unique=False)
    op.create_index(op.f('ix_cost_centers_company_id'), 'cost_centers', ['company_id'], unique=False)
    op.create_index(op.f('ix_cost_centers_manager_user_id'), 'cost_centers', ['manager_user_id'], unique=False)
    op.create_table('dataset_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_type', sa.String(length=30), nullable=False),
    sa.Column('scope_key', sa.String(length=80), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('last_closed_period', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_dataset_versions_created_by_users')),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], name=op.f('fk_dataset_versions_import_batch_id_import_batches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_versions'))
    )
    op.create_index('ix_dataset_versions_scope', 'dataset_versions', ['dataset_type', 'scope_key', 'is_current'], unique=False)
    op.create_table('import_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('sheet', sa.String(length=100), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('column', sa.String(length=100), nullable=True),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], name=op.f('fk_import_errors_batch_id_import_batches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_errors'))
    )
    op.create_index(op.f('ix_import_errors_batch_id'), 'import_errors', ['batch_id'], unique=False)
    op.create_table('import_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(length=30), nullable=False),
    sa.Column('sheet', sa.String(length=100), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('natural_key', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], name=op.f('fk_import_rows_batch_id_import_batches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_rows'))
    )
    op.create_index('ix_import_rows_batch', 'import_rows', ['batch_id', 'status'], unique=False)
    op.create_table('scenario_multipliers',
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('contract_type_code', sa.String(length=20), nullable=False),
    sa.Column('multiplier', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['contract_type_code'], ['contract_types.code'], name=op.f('fk_scenario_multipliers_contract_type_code_contract_types')),
    sa.ForeignKeyConstraint(['scenario_id'], ['personnel_scenarios.id'], name=op.f('fk_scenario_multipliers_scenario_id_personnel_scenarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scenario_id', 'contract_type_code', name=op.f('pk_scenario_multipliers'))
    )
    op.create_table('actual_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_version_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('cost_center_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.SmallInteger(), nullable=False),
    sa.Column('period', sa.SmallInteger(), nullable=False),
    sa.Column('posting_date', sa.Date(), nullable=True),
    sa.Column('document_number', sa.String(length=30), nullable=True),
    sa.Column('document_type', sa.String(length=10), nullable=True),
    sa.Column('vendor_code', sa.String(length=30), nullable=True),
    sa.Column('vendor_name', sa.String(length=200), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_actual_entries_account_id_accounts')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_actual_entries_branch_id_branches')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_actual_entries_company_id_companies')),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], name=op.f('fk_actual_entries_cost_center_id_cost_centers')),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], name=op.f('fk_actual_entries_dataset_version_id_dataset_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actual_entries'))
    )
    op.create_index('ix_actual_dims', 'actual_entries', ['dataset_version_id', 'fiscal_year', 'cost_center_id', 'account_id', 'period'], unique=False)
    op.create_table('asset_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('asset_class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_class_id'], ['asset_classes.id'], name=op.f('fk_asset_items_asset_class_id_asset_classes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_items')),
    sa.UniqueConstraint('name', name=op.f('uq_asset_items_name'))
    )
    op.create_table('budget_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('cost_center_id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consolidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], name=op.f('fk_budget_submissions_cost_center_id_cost_centers')),
    sa.ForeignKeyConstraint(['version_id'], ['budget_versions.id'], name=op.f('fk_budget_submissions_version_id_budget_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_submissions')),
    sa.UniqueConstraint('version_id', 'cost_center_id', 'module', name=op.f('uq_budget_submissions_version_id_cost_center_id_module'))
    )
    op.create_index(op.f('ix_budget_submissions_cost_center_id'), 'budget_submissions', ['cost_center_id'], unique=False)
    op.create_index(op.f('ix_budget_submissions_version_id'), 'budget_submissions', ['version_id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('cost_center_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('contract_type_code', sa.String(length=20), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('admission_date', sa.Date(), nullable=True),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('is_csc', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('dataset_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name=op.f('fk_employees_area_id_areas')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_employees_branch_id_branches')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_employees_company_id_companies')),
    sa.ForeignKeyConstraint(['contract_type_code'], ['contract_types.code'], name=op.f('fk_employees_contract_type_code_contract_types')),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], name=op.f('fk_employees_cost_center_id_cost_centers')),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], name=op.f('fk_employees_dataset_version_id_dataset_versions')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_employees_department_id_departments')),
    sa.ForeignKeyConstraint(['position_id'], ['job_positions.id'], name=op.f('fk_employees_position_id_job_positions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees')),
    sa.UniqueConstraint('company_id', 'registration', name=op.f('uq_employees_company_id_registration'))
    )
    op.create_index(op.f('ix_employees_cost_center_id'), 'employees', ['cost_center_id'], unique=False)
    op.create_table('macro_assumptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_version_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('indicator', sa.String(length=120), nullable=False),
    sa.Column('segment', sa.String(length=80), nullable=True),
    sa.Column('source', sa.String(length=300), nullable=True),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('reference_date', sa.Date(), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], name=op.f('fk_macro_assumptions_dataset_version_id_dataset_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_macro_assumptions'))
    )
    op.create_table('reference_budget_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_version_id', sa.Integer(), nullable=False),
    sa.Column('scenario', sa.String(length=20), nullable=False),
    sa.Column('fiscal_year', sa.SmallInteger(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('cost_center_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.SmallInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_reference_budget_entries_account_id_accounts')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_reference_budget_entries_branch_id_branches')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_reference_budget_entries_company_id_companies')),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], name=op.f('fk_reference_budget_entries_cost_center_id_cost_centers')),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], name=op.f('fk_reference_budget_entries_dataset_version_id_dataset_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reference_budget_entries'))
    )
    op.create_index('ix_refbudget_dims', 'reference_budget_entries', ['dataset_version_id', 'fiscal_year', 'cost_center_id', 'account_id', 'period'], unique=False)
    op.create_table('user_scopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('cost_center_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_user_scopes_company_id_companies')),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], name=op.f('fk_user_scopes_cost_center_id_cost_centers')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_scopes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_scopes'))
    )
    op.create_index(op.f('ix_user_scopes_user_id'), 'user_scopes', ['user_id'], unique=False)
    op.create_table('account_justifications',
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_account_justifications_account_id_accounts')),
    sa.ForeignKeyConstraint(['submission_id'], ['budget_submissions.id'], name=op.f('fk_account_justifications_submission_id_budget_submissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_account_justifications_updated_by_users')),
    sa.PrimaryKeyConstraint('submission_id', 'account_id', name=op.f('pk_account_justifications'))
    )
    op.create_table('budget_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('cost_center_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('account_detail_id', sa.Integer(), nullable=True),
    sa.Column('line_type', sa.String(length=20), nullable=False),
    sa.Column('group_ref', sa.String(length=40), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('assumption', sa.Text(), nullable=True),
    sa.Column('supplier', sa.String(length=200), nullable=True),
    sa.Column('contract_manager', sa.String(length=200), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_detail_id'], ['account_details.id'], name=op.f('fk_budget_lines_account_detail_id_account_details')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_budget_lines_account_id_accounts')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_budget_lines_branch_id_branches')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_budget_lines_company_id_companies')),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], name=op.f('fk_budget_lines_cost_center_id_cost_centers')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_budget_lines_created_by_users')),
    sa.ForeignKeyConstraint(['package_id'], ['budget_packages.id'], name=op.f('fk_budget_lines_package_id_budget_packages')),
    sa.ForeignKeyConstraint(['submission_id'], ['budget_submissions.id'], name=op.f('fk_budget_lines_submission_id_budget_submissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_budget_lines_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_lines'))
    )
    op.create_index('ix_budget_lines_dims', 'budget_lines', ['submission_id', 'account_id'], unique=False)
    op.create_table('capex_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('cost_center_id', sa.Integer(), nullable=False),
    sa.Column('is_project', sa.Boolean(), nullable=False),
    sa.Column('project_type_code', sa.String(length=80), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('expected_cost_reduction', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('expected_revenue', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('priority', sa.String(length=30), nullable=True),
    sa.Column('budget_prev_year', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_capex_projects_branch_id_branches')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_capex_projects_company_id_companies')),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], name=op.f('fk_capex_projects_cost_center_id_cost_centers')),
    sa.ForeignKeyConstraint(['submission_id'], ['budget_submissions.id'], name=op.f('fk_capex_projects_submission_id_budget_submissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capex_projects'))
    )
    op.create_index(op.f('ix_capex_projects_submission_id'), 'capex_projects', ['submission_id'], unique=False)
    op.create_table('employee_benefits',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('benefit_code', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['benefit_code'], ['benefit_types.code'], name=op.f('fk_employee_benefits_benefit_code_benefit_types')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_benefits_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('employee_id', 'benefit_code', name=op.f('pk_employee_benefits'))
    )
    op.create_table('package_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['budget_packages.id'], name=op.f('fk_package_reviews_package_id_budget_packages')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_package_reviews_reviewer_id_users')),
    sa.ForeignKeyConstraint(['submission_id'], ['budget_submissions.id'], name=op.f('fk_package_reviews_submission_id_budget_submissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_reviews')),
    sa.UniqueConstraint('submission_id', 'package_id', name=op.f('uq_package_reviews_submission_id_package_id'))
    )
    op.create_table('personnel_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('movement_type', sa.String(length=30), nullable=False),
    sa.Column('effective_month', sa.SmallInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('new_salary', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('contract_type_code', sa.String(length=20), nullable=True),
    sa.Column('cost_center_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('multiplier_override', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('severance_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name=op.f('fk_personnel_movements_area_id_areas')),
    sa.ForeignKeyConstraint(['contract_type_code'], ['contract_types.code'], name=op.f('fk_personnel_movements_contract_type_code_contract_types')),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], name=op.f('fk_personnel_movements_cost_center_id_cost_centers')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_personnel_movements_department_id_departments')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_personnel_movements_employee_id_employees')),
    sa.ForeignKeyConstraint(['position_id'], ['job_positions.id'], name=op.f('fk_personnel_movements_position_id_job_positions')),
    sa.ForeignKeyConstraint(['submission_id'], ['budget_submissions.id'], name=op.f('fk_personnel_movements_submission_id_budget_submissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personnel_movements'))
    )
    op.create_index(op.f('ix_personnel_movements_submission_id'), 'personnel_movements', ['submission_id'], unique=False)
    op.create_table('workflow_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('version_label', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['budget_submissions.id'], name=op.f('fk_workflow_events_submission_id_budget_submissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workflow_events_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_events'))
    )
    op.create_index(op.f('ix_workflow_events_submission_id'), 'workflow_events', ['submission_id'], unique=False)
    op.create_table('budget_line_values',
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.SmallInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['budget_lines.id'], name=op.f('fk_budget_line_values_line_id_budget_lines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('line_id', 'month', name=op.f('pk_budget_line_values'))
    )
    op.create_table('capex_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('asset_item_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('useful_life_months', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_capex_items_account_id_accounts')),
    sa.ForeignKeyConstraint(['asset_item_id'], ['asset_items.id'], name=op.f('fk_capex_items_asset_item_id_asset_items')),
    sa.ForeignKeyConstraint(['project_id'], ['capex_projects.id'], name=op.f('fk_capex_items_project_id_capex_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capex_items'))
    )
    op.create_index(op.f('ix_capex_items_project_id'), 'capex_items', ['project_id'], unique=False)
    op.create_table('capex_item_values',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.SmallInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['capex_items.id'], name=op.f('fk_capex_item_values_item_id_capex_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'month', name=op.f('pk_capex_item_values'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('capex_item_values')
    op.drop_index(op.f('ix_capex_items_project_id'), table_name='capex_items')
    op.drop_table('capex_items')
    op.drop_table('budget_line_values')
    op.drop_index(op.f('ix_workflow_events_submission_id'), table_name='workflow_events')
    op.drop_table('workflow_events')
    op.drop_index(op.f('ix_personnel_movements_submission_id'), table_name='personnel_movements')
    op.drop_table('personnel_movements')
    op.drop_table('package_reviews')
    op.drop_table('employee_benefits')
    op.drop_index(op.f('ix_capex_projects_submission_id'), table_name='capex_projects')
    op.drop_table('capex_projects')
    op.drop_index('ix_budget_lines_dims', table_name='budget_lines')
    op.drop_table('budget_lines')
    op.drop_table('account_justifications')
    op.drop_index(op.f('ix_user_scopes_user_id'), table_name='user_scopes')
    op.drop_table('user_scopes')
    op.drop_index('ix_refbudget_dims', table_name='reference_budget_entries')
    op.drop_table('reference_budget_entries')
    op.drop_table('macro_assumptions')
    op.drop_index(op.f('ix_employees_cost_center_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_budget_submissions_version_id'), table_name='budget_submissions')
    op.drop_index(op.f('ix_budget_submissions_cost_center_id'), table_name='budget_submissions')
    op.drop_table('budget_submissions')
    op.drop_table('asset_items')
    op.drop_index('ix_actual_dims', table_name='actual_entries')
    op.drop_table('actual_entries')
    op.drop_table('scenario_multipliers')
    op.drop_index('ix_import_rows_batch', table_name='import_rows')
    op.drop_table('import_rows')
    op.drop_index(op.f('ix_import_errors_batch_id'), table_name='import_errors')
    op.drop_table('import_errors')
    op.drop_index('ix_dataset_versions_scope', table_name='dataset_versions')
    op.drop_table('dataset_versions')
    op.drop_index(op.f('ix_cost_centers_manager_user_id'), table_name='cost_centers')
    op.drop_index(op.f('ix_cost_centers_company_id'), table_name='cost_centers')
    op.drop_index(op.f('ix_cost_centers_code'), table_name='cost_centers')
    op.drop_table('cost_centers')
    op.drop_table('benefit_types')
    op.drop_table('asset_classes')
    op.drop_table('account_details')
    op.drop_table('user_roles')
    op.drop_table('travel_rates')
    op.drop_table('travel_fares')
    op.drop_table('personnel_scenarios')
    op.drop_index(op.f('ix_package_managers_cycle_id'), table_name='package_managers')
    op.drop_table('package_managers')
    op.drop_index(op.f('ix_import_batches_status'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_file_sha256'), table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_table('cycle_parameters')
    op.drop_index(op.f('ix_budget_versions_cycle_id'), table_name='budget_versions')
    op.drop_table('budget_versions')
    op.drop_index(op.f('ix_branches_company_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('areas')
    op.drop_index(op.f('ix_accounts_package_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_index(op.f('ix_lookup_values_domain'), table_name='lookup_values')
    op.drop_table('lookup_values')
    op.drop_table('job_positions')
    op.drop_table('departments')
    op.drop_table('contract_types')
    op.drop_table('companies')
    op.drop_table('budget_packages')
    op.drop_table('budget_cycles')
    # ### end Alembic commands ###
